from dataclasses import dataclass
import json

from lib.util import group_dict_keys


@dataclass
class AABB:
    min: (float, float, float)
    max: (float, float, float)


@dataclass
class BlockStateShape:
    properties: dict[str, str]
    shape: [AABB]


def parse_shape(s: str) -> [AABB]:
    """
    Converts a shape of the form [AABB[x, y, z] -> [x, y, z], ...] into an AABB list
    """

    bounding_boxes = eval(
        s.replace("AABB", "(")
        .replace(", (", "), (")
        .replace(" ->", ",")
        .replace("]]", "])]")
    )
    return [
        AABB(min=min_corner, max=max_corner)
        for min_corner, max_corner in bounding_boxes
    ]


def shape_to_snbt(shape: [AABB]) -> str:
    snbt_string = ",".join([f"{{min: {aabb.min}, max: {aabb.max}}}" for aabb in shape])
    return f"[{snbt_string}]"


def properties_predicate(properties: dict[str, str]) -> str:
    """
    Converts a map of block state properties into the corresponding predicate
    Example: {"waterlogged": "true"} -> "[waterlogged=true]"
    """

    if properties:
        return (
            "["
            + ", ".join(
                map(
                    lambda prop: "{}={}".format(prop, str(properties[prop]).lower()),
                    properties.keys(),
                )
            )
            + "]"
        )
    else:
        return ""


def remove_useless_properties(block: [BlockStateShape]) -> [BlockStateShape]:
    """
    Filters out properties that do not affect the block shape (e.g. waterlogged) from a
    list of BlockStateShapes containing all possible block state properties of a block
    """

    # Get all property names
    properties = list(block[0].properties.keys())

    for property in properties:
        # List all values this property can have (e.g. ["false", "true"] if property is "waterlogged")
        values = set(state.properties[property] for state in block)

        # For each possible value of this property, get the list of possible block shapes with this value
        shapes = {}
        for value in values:
            shapes[value] = [
                state.shape for state in block if state.properties[property] == value
            ]

        # If the list is the same no matter the value (i.e. this property does not affect block shape), remove this property and remove duplicates
        first_shape = next(iter(shapes.values()))
        if all(shape == first_shape for shape in shapes.values()):
            first_value = list(values)[0]
            block = [
                state for state in block if state.properties[property] == first_value
            ]
            for state in block:
                state.properties.pop(property)

    return block


def get_block_data(filename: str) -> ([[str]], dict[str, [BlockStateShape]]):
    """
    Reads a JSON report of block hitboxes as generated by IrisDataGen and returns:
    * The list of block groups with the same shape data
    * A sanitized report of block hitboxes, with only one block per shape group
    """

    with open(filename) as blocks_file:
        block_data = json.load(
            blocks_file,
            object_hook=(
                lambda s: (
                    BlockStateShape(s["properties"], parse_shape(s["shape"]))
                    if ("properties" in s and "shape" in s)
                    else s
                )
            ),
        )

    for block in block_data:
        block_data[block] = remove_useless_properties(block_data[block])

    block_shape_groups = group_dict_keys(block_data)
    block_data = {group[0]: block_data[group[0]] for group in block_shape_groups}

    return block_shape_groups, block_data
